version: '3.1'

services:
  nginx:
    build:
      context: nginx/
      dockerfile: nginx.Dockerfile
    image: arturosoucase/flask-celery-example-nginx
    ports:
      - "80:80"

  app:
    build:
      context: .
      dockerfile: docker/app.Dockerfile
    image: arturosoucase/flask-celery-example-app
    environment:
      SECRET_KEY: 2e86f69da10590a2162929fc14d1ddcf24cf17e0bfec4f78
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_HOST: ${POSTGRES_HOST}
      POSTGRES_DB: ${POSTGRES_DB}
      RABBITMQ_USER: ${RABBITMQ_USER}
      RABBITMQ_HOST: ${RABBITMQ_HOST}
    depends_on:
      - rabbitmq
      - db

  rabbitmq:
    image: rabbitmq
    ports:
      - "5672:5672"

  db:
    image: postgres:10-alpine
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"

  worker1:
    build:
      context: .
      dockerfile: docker/worker.Dockerfile
    image: arturosoucase/flask-celery-example-worker
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_HOST: ${POSTGRES_HOST}
      POSTGRES_DB: ${POSTGRES_DB}
      RABBITMQ_USER: ${RABBITMQ_USER}
      RABBITMQ_HOST: ${RABBITMQ_HOST}
    depends_on:
      - rabbitmq

  flower:
    build:
      context: .
      dockerfile: docker/flower.Dockerfile
    image: arturosoucase/flask-celery-example-flower
    ports:
      - "5555:5555"
