version: '3.1'

services:
  nginx:
    build:
      context: nginx/
      dockerfile: nginx.Dockerfile
    image: arturosoucase/flask-celery-example-nginx
    ports:
      - "80:80"

  app:
    build:
      context: .
      dockerfile: app.Dockerfile
    image: arturosoucase/flask-celery-example-app
    depends_on:
      - rabbitmq
      - db

  rabbitmq:
    image: rabbitmq
    ports:
      - "5672:5672"

  db:
    image: postgres:10-alpine
    environment:
      POSTGRES_USER: demo
      POSTGRES_PASSWORD: pass
    ports:
      - "5432:5432"

  worker1:
    build:
      context: .
      dockerfile: worker.Dockerfile
    image: arturosoucase/flask-celery-example-worker
    depends_on:
      - rabbitmq

  flower:
    build:
      context: .
      dockerfile: flower.Dockerfile
    image: arturosoucase/flask-celery-example-flower
    ports:
      - "5555:5555"
