apiVersion: v1
kind: Secret
metadata:
  name: db-secret
  namespace: flask-celery
type: Opaque
data:
  POSTGRES_DB: ZGVtbw==
  POSTGRES_HOST: cG9zdGdyZXM=
  POSTGRES_PASSWORD: cGFzcw==
  POSTGRES_USER: ZGVtbw==