apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: rabbitmq
  name: rabbitmq
  namespace: flask-celery
spec:
  ports:
  - name: client-port
    port: 5672
    protocol: TCP
    targetPort: 5672
  selector:
    app: rabbitmq
  type: ClusterIP
status:
  loadBalancer: {}