apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: uwsgi-app
  name: app
  namespace: flask-celery
spec:
  ports:
  - name: uwsgi-app-port
    port: 9000
    protocol: TCP
    targetPort: 9000
  selector:
    app: uwsgi-app
  type: ClusterIP
status:
  loadBalancer: {}

