apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: flower
  name: flower
  namespace: flask-celery
spec:
  ports:
  - name: http
    port: 5555
    protocol: TCP
    targetPort: 5555
    nodePort: 30082
  selector:
    app: flower
  type: NodePort
status:
  loadBalancer: {}